### ISSUE TITLE
Volume Tests failing with Sqlite on Windows

### ISSUE THREAD

**Issue by ericziethen** [ericziethen/django-property-filter#177]
This seems to be the max parameter limitation issue again.

- [x] Fix issue
- [x] Maybe use 999 as default for sqlite_max as not sure what it's compiled with, then give the user a way of increasing it
- [x] Enable Windows Volume test in Github Actions

**Comment by ericziethen** [comment]
Just running the Volume Test in the test project and querying by boolean already crashes with something like

'''
Traceback (most recent call last):
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\# Eric Projects\django-property-filter\django_property_filter\utils.py", line 140, in filter_qs_by_pk_list
    result_qs.count()
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\models\query.py", line 411, in count
    return self.query.get_count(using=self.db)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\models\sql\query.py", line 515, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\models\sql\query.py", line 500, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: too many SQL variables

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: Expression tree is too large (maximum depth 1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django_filters\views.py", line 81, in get
    self.object_list = self.filterset.qs
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "D:\# Eric Projects\django-property-filter\django_property_filter\filtersets.py", line 65, in filter_queryset
    queryset = filter_qs_by_pk_list(queryset, pk_list, preserve_order=preserve_order)
  File "D:\# Eric Projects\django-property-filter\django_property_filter\utils.py", line 163, in filter_qs_by_pk_list
    logging.warning(F'Only returning the first {result_qs.count()} items because of max parameter '
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\models\query.py", line 411, in count
    return self.query.get_count(using=self.db)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\models\sql\query.py", line 515, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\models\sql\query.py", line 500, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Expression tree is too large (maximum depth 1000)
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 50497)
Traceback (most recent call last):
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 50540)
Traceback (most recent call last):
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "D:\# Eric Projects\django-property-filter\.venv\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
'''

**Comment by ericziethen** [comment]
it seems like the sqlite version was 3.33.0 which should have a higher limit than 999, but maybe it's compiled with less?
